import type { Contact, Notification, PaymentRequest, Task, UserPreferences, Workspace } from '@/types';
import type { Tenant } from '@/types/tenant';
import type { User } from '@/types/auth';

const jsonArray = <T>(value: unknown, fallback: T[] = []): T[] =>
  Array.isArray(value) ? value as T[] : fallback;

export const profileFromRow = (row: any): User => ({
  id: row.id,
  username: row.username ?? row.email,
  displayName: row.display_name ?? row.email,
  email: row.email,
  passwordHash: '',
  salt: '',
  role: row.role,
  tenantId: row.tenant_id,
  workspaceAccess: row.workspace_access ?? [],
  isActive: row.is_active ?? true,
  mfaEnabled: row.mfa_enabled ?? false,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
  lastLoginAt: row.last_login_at ?? null,
  createdBy: row.created_by,
});

export const tenantFromRow = (row: any): Tenant => ({
  id: row.id,
  name: row.name,
  slug: row.slug,
  colour: row.colour,
  plan: row.plan,
  status: row.status,
  settings: row.settings ?? {},
  contactName: row.contact_name ?? '',
  contactEmail: row.contact_email ?? '',
  notes: row.notes ?? '',
  createdAt: row.created_at,
  updatedAt: row.updated_at,
  createdBy: row.created_by ?? '',
});

export const tenantToInsert = (tenant: Omit<Tenant, 'createdAt' | 'updatedAt'>) => ({
  id: tenant.id,
  name: tenant.name,
  slug: tenant.slug,
  colour: tenant.colour,
  plan: tenant.plan,
  status: tenant.status,
  settings: tenant.settings,
  contact_name: tenant.contactName,
  contact_email: tenant.contactEmail,
  notes: tenant.notes,
  created_by: tenant.createdBy || null,
});

export const workspaceFromRow = (row: any): Workspace => ({
  id: row.id,
  tenantId: row.tenant_id,
  name: row.name,
  type: row.type,
  colour: row.colour,
  currency: row.currency ?? 'GBP',
  isDefault: row.is_default,
  isArchived: row.is_archived,
  hideFinanceFeatures: row.hide_finance_features,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

export const workspaceToInsert = (workspace: Omit<Workspace, 'createdAt' | 'updatedAt'>) => ({
  id: workspace.id,
  tenant_id: workspace.tenantId,
  name: workspace.name,
  type: workspace.type,
  colour: workspace.colour,
  currency: workspace.currency,
  is_default: workspace.isDefault,
  is_archived: workspace.isArchived,
  hide_finance_features: workspace.hideFinanceFeatures,
});

export const preferencesFromRow = (row: any, fallback: UserPreferences): UserPreferences => ({
  ...fallback,
  ...(row?.preferences ?? {}),
  activeWorkspaceId: row?.active_workspace_id ?? row?.preferences?.activeWorkspaceId ?? fallback.activeWorkspaceId,
});

export const taskFromRow = (row: any): Task => ({
  id: row.id,
  tenantId: row.tenant_id,
  workspaceId: row.workspace_id,
  title: row.title,
  description: row.description ?? '',
  category: row.category,
  status: row.status,
  priority: row.priority,
  dueDate: row.due_date,
  assignedTo: row.assigned_to,
  assignedToName: row.assigned_to_name,
  assignedToEmail: row.assigned_to_email,
  delegatedBy: row.delegated_by,
  notes: row.notes ?? '',
  attachments: jsonArray(row.attachments),
  checklist: jsonArray(row.checklist),
  recurrence: row.recurrence,
  reminder: row.reminder,
  parentTaskId: row.parent_task_id,
  linkedPaymentRequestId: row.linked_payment_request_id,
  tags: row.tags ?? [],
  createdAt: row.created_at,
  updatedAt: row.updated_at,
  completedAt: row.completed_at,
});

export const taskToInsert = (task: Omit<Task, 'createdAt' | 'updatedAt'>) => ({
  id: task.id,
  tenant_id: task.tenantId,
  workspace_id: task.workspaceId,
  title: task.title,
  description: task.description,
  category: task.category,
  status: task.status,
  priority: task.priority,
  due_date: task.dueDate,
  assigned_to: task.assignedTo,
  assigned_to_name: task.assignedToName,
  assigned_to_email: task.assignedToEmail,
  delegated_by: null,
  notes: task.notes,
  attachments: task.attachments ?? [],
  checklist: task.checklist ?? [],
  recurrence: task.recurrence,
  reminder: task.reminder,
  parent_task_id: task.parentTaskId,
  linked_payment_request_id: task.linkedPaymentRequestId,
  tags: task.tags ?? [],
  completed_at: task.completedAt,
});

export const taskUpdatesToRow = (updates: Partial<Task>) => ({
  ...(updates.workspaceId !== undefined && { workspace_id: updates.workspaceId }),
  ...(updates.title !== undefined && { title: updates.title }),
  ...(updates.description !== undefined && { description: updates.description }),
  ...(updates.category !== undefined && { category: updates.category }),
  ...(updates.status !== undefined && { status: updates.status }),
  ...(updates.priority !== undefined && { priority: updates.priority }),
  ...(updates.dueDate !== undefined && { due_date: updates.dueDate }),
  ...(updates.assignedTo !== undefined && { assigned_to: updates.assignedTo }),
  ...(updates.assignedToName !== undefined && { assigned_to_name: updates.assignedToName }),
  ...(updates.assignedToEmail !== undefined && { assigned_to_email: updates.assignedToEmail }),
  ...(updates.notes !== undefined && { notes: updates.notes }),
  ...(updates.attachments !== undefined && { attachments: updates.attachments }),
  ...(updates.checklist !== undefined && { checklist: updates.checklist }),
  ...(updates.recurrence !== undefined && { recurrence: updates.recurrence }),
  ...(updates.reminder !== undefined && { reminder: updates.reminder }),
  ...(updates.parentTaskId !== undefined && { parent_task_id: updates.parentTaskId }),
  ...(updates.linkedPaymentRequestId !== undefined && { linked_payment_request_id: updates.linkedPaymentRequestId }),
  ...(updates.tags !== undefined && { tags: updates.tags }),
  ...(updates.completedAt !== undefined && { completed_at: updates.completedAt }),
  updated_at: new Date().toISOString(),
});

export const paymentFromRow = (row: any): PaymentRequest => ({
  id: row.id,
  tenantId: row.tenant_id,
  workspaceId: row.workspace_id,
  supplier: row.supplier,
  project: row.project ?? '',
  description: row.description ?? '',
  amount: Number(row.amount ?? 0),
  vatAmount: Number(row.vat_amount ?? 0),
  totalAmount: Number(row.total_amount ?? 0),
  currency: row.currency ?? 'GBP',
  vatCode: row.vat_code ?? 'S',
  vatBreakdown: jsonArray(row.vat_breakdown),
  dueDate: row.due_date,
  requestedBy: row.requested_by ?? '',
  approvalStatus: row.approval_status,
  paymentStatus: row.payment_status,
  approvedBy: row.approved_by,
  approvedAt: row.approved_at,
  paidAt: row.paid_at,
  scheduledDate: row.scheduled_date,
  notes: row.notes ?? '',
  linkedTaskId: row.linked_task_id,
  recurrence: row.recurrence,
  invoiceReference: row.invoice_reference ?? '',
  purchaseOrderNumber: row.purchase_order_number ?? '',
  attachments: jsonArray(row.attachments),
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

export const paymentToInsert = (payment: Omit<PaymentRequest, 'createdAt' | 'updatedAt'>) => ({
  id: payment.id,
  tenant_id: payment.tenantId,
  workspace_id: payment.workspaceId,
  supplier: payment.supplier,
  project: payment.project,
  description: payment.description,
  amount: payment.amount,
  vat_amount: payment.vatAmount,
  total_amount: payment.totalAmount,
  currency: payment.currency,
  vat_code: payment.vatCode,
  vat_breakdown: payment.vatBreakdown ?? [],
  due_date: payment.dueDate,
  requested_by: payment.requestedBy,
  approval_status: payment.approvalStatus,
  payment_status: payment.paymentStatus,
  approved_by: payment.approvedBy,
  approved_at: payment.approvedAt,
  paid_at: payment.paidAt,
  scheduled_date: payment.scheduledDate,
  notes: payment.notes,
  linked_task_id: payment.linkedTaskId,
  recurrence: payment.recurrence,
  invoice_reference: payment.invoiceReference,
  purchase_order_number: payment.purchaseOrderNumber,
  attachments: payment.attachments ?? [],
});

export const paymentUpdatesToRow = (updates: Partial<PaymentRequest>) => ({
  ...(updates.workspaceId !== undefined && { workspace_id: updates.workspaceId }),
  ...(updates.supplier !== undefined && { supplier: updates.supplier }),
  ...(updates.project !== undefined && { project: updates.project }),
  ...(updates.description !== undefined && { description: updates.description }),
  ...(updates.amount !== undefined && { amount: updates.amount }),
  ...(updates.vatAmount !== undefined && { vat_amount: updates.vatAmount }),
  ...(updates.totalAmount !== undefined && { total_amount: updates.totalAmount }),
  ...(updates.currency !== undefined && { currency: updates.currency }),
  ...(updates.vatCode !== undefined && { vat_code: updates.vatCode }),
  ...(updates.vatBreakdown !== undefined && { vat_breakdown: updates.vatBreakdown }),
  ...(updates.dueDate !== undefined && { due_date: updates.dueDate }),
  ...(updates.requestedBy !== undefined && { requested_by: updates.requestedBy }),
  ...(updates.approvalStatus !== undefined && { approval_status: updates.approvalStatus }),
  ...(updates.paymentStatus !== undefined && { payment_status: updates.paymentStatus }),
  ...(updates.approvedBy !== undefined && { approved_by: updates.approvedBy }),
  ...(updates.approvedAt !== undefined && { approved_at: updates.approvedAt }),
  ...(updates.paidAt !== undefined && { paid_at: updates.paidAt }),
  ...(updates.scheduledDate !== undefined && { scheduled_date: updates.scheduledDate }),
  ...(updates.notes !== undefined && { notes: updates.notes }),
  ...(updates.linkedTaskId !== undefined && { linked_task_id: updates.linkedTaskId }),
  ...(updates.recurrence !== undefined && { recurrence: updates.recurrence }),
  ...(updates.invoiceReference !== undefined && { invoice_reference: updates.invoiceReference }),
  ...(updates.purchaseOrderNumber !== undefined && { purchase_order_number: updates.purchaseOrderNumber }),
  ...(updates.attachments !== undefined && { attachments: updates.attachments }),
  updated_at: new Date().toISOString(),
});

export const contactFromRow = (row: any): Contact => ({
  id: row.id,
  tenantId: row.tenant_id,
  workspaceId: row.workspace_id,
  name: row.name,
  email: row.email ?? '',
  role: row.role ?? '',
  company: row.company ?? '',
  phone: row.phone ?? '',
  notes: row.notes ?? '',
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

export const contactToInsert = (contact: Omit<Contact, 'createdAt' | 'updatedAt'>) => ({
  id: contact.id,
  tenant_id: contact.tenantId,
  workspace_id: contact.workspaceId,
  name: contact.name,
  email: contact.email,
  role: contact.role,
  company: contact.company,
  phone: contact.phone,
  notes: contact.notes,
});

export const notificationFromRow = (row: any): Notification => ({
  id: row.id,
  tenantId: row.tenant_id,
  workspaceId: row.workspace_id,
  type: row.type,
  title: row.title,
  message: row.message,
  relatedId: row.related_id,
  relatedType: row.related_type,
  isRead: row.is_read,
  isDismissed: row.is_dismissed,
  snoozedUntil: row.snoozed_until,
  createdAt: row.created_at,
});

export const notificationToInsert = (notification: Omit<Notification, 'createdAt'>) => ({
  id: notification.id,
  tenant_id: notification.tenantId,
  workspace_id: notification.workspaceId,
  type: notification.type,
  title: notification.title,
  message: notification.message,
  related_id: notification.relatedId,
  related_type: notification.relatedType,
  is_read: notification.isRead,
  is_dismissed: notification.isDismissed,
  snoozed_until: notification.snoozedUntil,
});
